### PR TITLE
Fix: Removed invalid CodeSandbox links

### LINKED ISSUE #223: Online documentation references non-existent CodeSandbox components
There may be others, but these are the two I have stumbled upon...

https://v2.grommet.io/list references https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/list&module=%2Fsrc%2FList.js

https://v2.grommet.io/drop references https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/drop&module=%2Fsrc%2FDrop.js

### PR DESCRIPTION
**Pull request by jlaluces123**
This PR aims to:
- Resolve #223
- Removes codesandbox links from components that do not have a corresponding sandbox

### CODE REVIEW

File: src/screens/SkipLinks.js [hunk 1]
```diff
@@ -31,12 +31,6 @@ export default () => (
             'https://cdn-images-1.medium.com/fit/c/120/120/1*TD1P0HtIH9zF0UEH28zYtw.png',
           label: 'Storybook',
         },
-        {
-          url:
-            'https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/skiplinks&module=%2Fsrc%2FSkipLinks.js',
```
Comment (jcfilben) [inline src/screens/SkipLinks.js:36]: There is a codesandbox for Skip Links, it is just named Skip Link. The url should be changed to `url: 'https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/skiplinks&module=%2Fsrc%2FSkipLink.js'`

Comment (jlaluces123) [reply src/screens/SkipLinks.js]: Thanks for the catch, added the url in! 🙏

**Review by ericsoderberghp — APPROVED** [review]
