### PR TITLE
Fix prop anchor links to scroll to location

### LINKED ISSUE #294: Doc links to specific props not scrolling down the page
A link that references a specific prop on a component page should scroll down to that section when you open it, but instead the link opens, goes to the specific prop section and then takes you back to the top of the page.
Example: https://v2.grommet.io/list#onOrder

### PR DESCRIPTION
**Pull request by jcfilben**
Fixes doc links that reference a specific prop on a component page to scroll down to that section when you navigate to the link.
Closes #294

### CODE REVIEW

File: src/components/Page.js [hunk 1]
```diff
@@ -1,16 +1,37 @@
...
 
-Page.propTypes = Box.propTypes;
+  componentDidUpdate() {
+    this.scrollToSection();
+  }
+
+  scrollToSection = () => {
+    const name = window.location.hash.split('#')[1];
+    if (name) {
+      document.getElementById(name).scrollIntoView({
```
Comment (ericsoderberghp) [inline src/components/Page.js:17]: Doesn't the browser already do this?
https://stackoverflow.com/questions/19299220/is-there-an-event-that-fires-when-a-browser-scrolls-to-a-named-anchor

Comment (jcfilben) [reply src/components/Page.js:17]: The browser supplied event doesn't fire when you go to a url with the hash already set. It only works if you are already on the same page

**Review by ericsoderberghp — APPROVED** [review]
